title: bin jek 
email: binbotaro3@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description. 
twitter_username: binbotaro3
github_username: binbotaro3 

# Build settings
theme: minima
plugins:
  - jekyll-feed

domain: binbotaro.github.io
url: hhttps://binbotaro.github.io
# baseurl: /jek

